version: "2"

services:
  # load balancer
  lb:
    container_name: interlockexample_lb
    image: nginx:1.9
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    restart: always
    networks:
      - backend
    ports:
      - "80:80"
    labels:
      - "interlock.ext.name=nginx"
    environment:
      - constraint:node==*n1

  # app
  app:
    image: ehazlett/docker-demo
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 8080
    labels:
        - "interlock.hostname=test"
        - "interlock.domain=local"

networks:
  backend: {}
