version: "2"

services:
  # load balancer
  lb:
    container_name: interlockexample_lb
    image: nginx:1.9
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "80:80"
    labels:
      - "interlock.ext.name=nginx"
    environment:
      - constraint:node==*n1

  # app
  app:
    image: ehazlett/docker-demo
    restart: unless-stopped
    networks:
      - backend
    expose:
      - 8080
    labels:
      - "interlock.network=interlockexample_backend"
      - "interlock.hostname=test"
      - "interlock.domain=local"
    depends_on:
      - lb

networks:
  backend: {}
